#!/usr/bin/env python3
import sys
import json


FFI_TYPE_MAP = {
    ":void": "v",
    ":int": "i",
    ":unsigned-char": "B",
    ":short": "h",
    ":unsigned-int": "I",
    "uint8_t": "B",
    "uint16_t": "H",
    "uint32_t": "I",
    "ssize_t": "l",
}

UCTYPES_TYPE_MAP = {
    ":void": "uctypes.VOID",
    ":unsigned-char": "uctypes.UINT8",
    ":short": "uctypes.INT16",
    ":int": "uctypes.INT32",
    ":unsigned-int": "uctypes.UINT32",
    ":enum": "uctypes.INT32",
    "uint8_t": "uctypes.UINT8",
    "uint16_t": "uctypes.UINT16",
}

def conv_ffi_type(rec):
    if rec["tag"] == ":pointer":
        return "p"
    if rec["tag"] in FFI_TYPE_MAP:
        return FFI_TYPE_MAP[rec["tag"]]
    assert 0, rec["tag"]

def conv_uctypes_type(rec, offset):
    if rec["tag"] in UCTYPES_TYPE_MAP:
        v = UCTYPES_TYPE_MAP[rec["tag"]]
        if "%d" in v:
            return v % offset
        else:
            return "%s | %d" % (v, offset)
    if rec["tag"] == ":pointer":
        if rec["type"]["tag"] == ":struct":
            return "(uctypes.PTR | %d, %s)" % (offset, rec["type"]["name"])
        else:
            if rec["type"]["tag"] not in UCTYPES_TYPE_MAP:
                assert 0, rec
            return "(uctypes.PTR | %d, %s)" % (offset, UCTYPES_TYPE_MAP[rec["type"]["tag"]])
    assert 0, rec["tag"]


f = open(sys.argv[1])
data = json.load(f)

print("import ffi")
print("import uctypes")
print()
print('l = ffi.open("libusb-1.0.so.0")')
print()


for desc in data:
    if not desc["location"].startswith("libusb.h:"):
        continue
    if desc["tag"] == "function":
        params = [conv_ffi_type(x["type"]) for x in desc["parameters"]]
        s = '%s = l.func(%r, "%s", %r)' % (desc["name"], conv_ffi_type(desc["return-type"]), desc["name"], "".join(params))
        if desc.get("inline", False):
            print("#%s" % s)
        else:
            print(s)
    elif desc["tag"] == "enum":
        print("# %s" % desc["name"])
        for f in desc["fields"]:
            print("%s = %s" % (f["name"], f["value"]))
    elif desc["tag"] == "struct":
        print("%s = {" % desc["name"])
        for f in desc["fields"]:
            print('    "%s": %s,' % (f["name"], conv_uctypes_type(f["type"], f["bit-offset"] / 8)))
#            print(f)
        if desc["bit-size"] != 0:
            # This doesn't have to be true due to alignment
            #assert desc["bit-size"] == f["bit-offset"] + f["bit-size"]
            pass
#        print(desc)
        print("}")
    elif desc["tag"] == "typedef":
        if desc["type"]["tag"] == ":struct":
            FFI_TYPE_MAP[desc["name"]] = desc["type"]["name"]
            UCTYPES_TYPE_MAP[desc["name"]] = desc["type"]["name"]
            print("# typedef %s" % desc["name"])
        elif desc["type"]["tag"] == ":function-pointer":
            FFI_TYPE_MAP[desc["name"]] = "C"
            UCTYPES_TYPE_MAP[desc["name"]] = "(uctypes.PTR | %d, uctypes.VOID)"
            print("# typedef func-ptr %s" % desc["name"])
        else:
            print(desc)
            assert 0, desc["tag"]
    else:
        print(desc)
        assert 0, desc["tag"]
        pass
